### ISSUE TITLE
After 24.4.2 installed, PumpSpy won't initialize on restart

### ISSUE THREAD

**Issue by mel-barnum** [Crewski/Pumpspy-HA#14]
Yesterday I installed HA Core 2024.4.2  and all my tracking of pump output stopped.

Log from HA Core

Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 12:22:23 PM (1 occurrences)
Last logged: 12:22:23 PM

Error setting up entry Pumpspy () for pumpspy_ha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pumpspy_ha/__init__.py", line 47, in async_setup_entry
    await api.setup()
  File "/config/custom_components/pumpspy_ha/pypumpspy.py", line 66, in setup
    await self.get_uid(session=session)
  File "/config/custom_components/pumpspy_ha/pypumpspy.py", line 135, in get_uid
    raise InvalidAccessToken
custom_components.pumpspy_ha.pypumpspy.InvalidAccessToken

**Comment by mel-barnum** [comment]
This issue has been open for more than 45 days and no response yet.  Is this still being supported?  I hope so because I find it to be very useful to my HA installation.

**Comment by gtbdf1** [comment]
@Crewski hope everything is ok...
