### ISSUE TITLE
Sensors all show zero values

### ISSUE THREAD

**Issue by oester** [Crewski/Pumpspy-HA#4]
I just installed the latest version and the sensors seem to show all zero values. I would expect some of the daily values to be zero, but not things like RSSI.

<img width="331" alt="Screenshot 2023-01-20 at 11 50 03 AM" src="https://user-images.githubusercontent.com/13770069/213771639-1511be19-b00e-42ef-a9b4-6853be39ecdf.png">

**Comment by Crewski** [comment]
I've had a lot of issues with the calls to Pumpspy failing, I'll work on figuring that out.  Any change the values have been populated since you posted this?

**Comment by oester** [comment]
Nope, still the same.

**Comment by Crewski** [comment]
I rewrote the code to talk to the Pumpspy server, as well as some other stuff.  There is a beta version of v0.1.4.  If you already have an instance installed, you'll need to delete it first and then add a new one.  Hopefully this will fix your issue.  Let me know.

**Comment by oester** [comment]
Thanks, how do I install the the beta version using HACS? I don't see it listed

**Comment by oester** [comment]
NM, I forgot to select show beta versions

**Comment by oester** [comment]
After update an HA restart, it fails to start and I see this in the logs:

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/pumpspy_ha/pypumpspy.py:62
Integration: Pumpspy-HA
First occurred: 7:31:42 AM (1 occurrences)
Last logged: 7:31:42 AM

Error setting up entry Pumpspy (Basement Sump Pump) for pumpspy_ha
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 583, in write_bytes
    await self.body.write(writer)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/payload.py", line 247, in write
    await writer.write(self._value)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 116, in write
    self._write(chunk)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pumpspy_ha/__init__.py", line 40, in async_setup_entry
    await api.setup()
  File "/config/custom_components/pumpspy_ha/pypumpspy.py", line 38, in setup
    await self.get_token()
  File "/config/custom_components/pumpspy_ha/pypumpspy.py", line 62, in get_token
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://www.pumpspy.com:8081/oauth/token
`

**Comment by oester** [comment]
However, another restart - didn't fail but the values are all still zero. No other log entries.

**Comment by Crewski** [comment]
Is your system a pumpsy or pitboss+?  Not that I think it makes a difference though.  Does the  pumpspy/pitboss app on your phone have values populated?

**Comment by electric-ear** [comment]
I believe certain parts matter whether you are using a pumpspy or pitboss+.  I have a pumpsy and did some peeking awhile back with postman. With pumpspy, some of the URLs are different than what's in the code.

Here's what I noticed that would be different
CURRENT_URL = "/pump_outlets/deviceid/\<DEVICEID\>"
DAILY_URL = "/pump_outlet_cycles/deviceid/\<DEVICEID\>/interval/day"

**Comment by Crewski** [comment]
@electric-ear  thanks for the help!   I had made the assumption that everything from Pumpspy would be the same.  I have the Pitboss+ sump pump/backup battery system.  Using Postman I tried the URLs you listed.  The current url returned a lot of the same data, but didn't have any backup/battery info.  The daily url returned an empty array.  So it looks like I need to pay attention to what type of device it is.  It turns out I you can query other devices once you are authenticated, so I'll poke around and see what I can find.

@oester if you wanted me to look specifically at your device (I can't see location or anything, just the info it spits out) you can add this line `LOG.warning("Pumpspy device id: %s", self.device_id)` at the end of the __init__ in pypumspy.py so it looks like this:

```
class Pumpspy:
    """Python class to talk to Pumpspy API"""

    def __init__(self, username, password, device_id=None) -> None:
        """Initialize."""
        self.username = username
        self.password = password
        self.device_name = None
        self.device_id = device_id
        self.access_token = None
        self.uid = None
        self.lid = None
        LOG.warning("Pumpspy device id: %s", self.device_id)    #<--- add this line
```

Reboot and check your logs.  There should be a warning with your device it.  You can post it here or email me at davidnaylor04@gmail.com.  Also, let me know what type of pumpspy system you have.

**Comment by oester** [comment]
Sent device ID via email. model is PumpSpy PSMT2000.

**Comment by Crewski** [comment]
Thanks.  Sure enough a quick poke in Postman shows that your device uses the urls @electric-ear  posted.  It also seems like you can only get "day" requests, not "week" and "month" like the other url provides.  It appears I'll be able to use the iddevice_type to distinguish the difference (yours is 2, mine is 3).  I'll keep you updated.  I wonder how many device types there are out there.

**Comment by oester** [comment]
History - In the app, under "Cycle History" I can go back and see cycles per day, and if I drill into a particular day, I can see the individual cycles.

**Comment by electric-ear** [comment]
> Thanks. Sure enough a quick poke in Postman shows that your device uses the urls @electric-ear posted. It also seems like you can only get "day" requests, not "week" and "month" like the other url provides. It appears I'll be able to use the iddevice_type to distinguish the difference (yours is 2, mine is 3). I'll keep you updated. I wonder how many device types there are out there.

Instead of /day, you should be able do /week and /month to get the weekly and monthly, I recheck that when I'm able

**Comment by Crewski** [comment]
> Instead of /day, you should be able do /week and /month to get the weekly and monthly, I recheck that when I'm able

I tried to use "week" in Postman but it just kept spinning and never received anything back.

**Comment by Crewski** [comment]
@oester I just pushed a new beta release to HACS.  Give it a try and let me know if it work.  I added the ability to decide if you want weekly and monthly sensors or not.  You can pick them from the initial configuration, or configure it later via the integration.  For non-battery backup units, the weekly and monthly queries take a long time (up to 1 1/2 minutes each) so just keep that in mind.  You won't notice it when it does it in the background, but you will when you first initialize it.

**Comment by oester** [comment]
Hey, look good!

<img width="661" alt="Screenshot 2023-01-27 at 9 41 34 AM" src="https://user-images.githubusercontent.com/13770069/215126976-777f524a-606a-4e8e-96bc-f37205e20500.png">

**Comment by electric-ear** [comment]
To follow up on the the weekly/monthly taking a long time, depending on how long your device has been operation, probably a lot of data coming back. 
One of the requests in my postman trace shows paging http://www.pumpspy.com:8081/pump_outlet_cycles/deviceid/DEVICEID/interval/day/paged?page=0

You ought be able to replace "day" with "week" and that may come back quicker since it would only return the first "page".

**Comment by Crewski** [comment]
Thanks for the suggestion. I came across that endpoint when I was looking through the PumpSpy apk. I tried it, but had the page set to 1. The results weren’t right, which apparently is because I should have had page set to 0. I’ll test it out some and potentially make the change.

**Comment by sheastyer** [comment]
@Crewski what do you mean by the 'PumpSpy apk'? Looking into some sort of visualizations for myself and am trying to glean more info out of the API doc you wrote, would love to query by date, similar to how the app itself lets you look at all cycles for any given date.

**Comment by Crewski** [comment]
> @Crewski what do you mean by the 'PumpSpy apk'? Looking into some sort of visualizations for myself and am trying to glean more info out of the API doc you wrote, would love to query by date, similar to how the app itself lets you look at all cycles for any given date.

I used the latest app for android and decompiled the apk (app file).  Then sifted through a bunch of gibberish without line breaks.  Luckily the app was written in Angular (probably Ionic) which is something I'm familiar with.

Anyway, you'd be looking at making a call to the links below depending on the type of system you have.  The date is formatted as YYYY-MM-DD.  Don't forget to insert your device id.  For the GET request, the headers need to be content-type: application/json and  the authorization bearer token.

Battery backup:
`http://www.pumpspy.com:8081/bbs_cycles/deviceid/<insert your device id>/motor/ac/date/2023-03-03`

Pump Outlet:
`http://www.pumpspy.com:8081/pump_outlets_cycles/deviceid/<insert your device id>/date/2023-03-03`

Let me know if it works out for you.

**Comment by Crewski** [comment]
@sheastyer here is the decompiled file.  I named it ApiService.js.  Basically your calls are going to have `bbs`, `pump_outlets`, or `rht_outles `ahead of the `_cycles `part of the url.  If its bbs, you'll also need to add the` /motor/<ac or dc>/` part.
[ApiService.zip](https://github.com/Crewski/Pumpspy-HA/files/10898574/ApiService.zip)

**Comment by righteouskill100** [comment]
![image](https://github.com/Crewski/Pumpspy-HA/assets/144564808/f50ab5f8-c705-4b95-940f-7913bb658319)


I could use some assistance if people are willing. I am not seeing any data from the pump in HA. I have the basic pump spy outlet and I find it odd that all the sensors talk to battery backup, it makes me think that there is a new URL that gets called or that I need to call the right URL in the config files.

when I look at my logs i see "2024-04-05 19:46:26.232 ERROR (MainThread) [custom_components.pumpspy_ha.pypumpspy] Error fetching current data: {"timestamp":1712360786177,"status":404,"error":"Not Found","message":"No message available","path":"/rht_outlet_cycles/deviceid/(DEVICEID)/interval/day"}"  with this repeated for week, and month. The "rth makes me think it is calling the wrong URL.

Any help would be appreciated.

**Comment by righteouskill100** [comment]
Well since I got no replies for help, i did some digging to figure it out myself. In pypumpspy.py, there is a function "device_types". I enabled logging to see how the API responded and found that my device type was a 4. Looking at the "device_types" function, 4 had "rht_outlets" and "rht_outlet" however my device (pump spy outlet 2.0) should be using "pump_outlets" and "pump_outlet" for the "endpoint" and "interval_endpoint" respectively. once i changed those in the pypumpspy.py and reloaded HA, i started to get data coming in.
